name: Bracket

samples:
  count: 1000

parameters:
  format: csv
  file: LBracket_design_parameters.csv

qois:
  format: csv
  file: LBracket_QoIs.csv

thumbnails:
  format: png
  files: images/?.png
  padZeroes: false
  offset: 1

distances:
  format: csv
  file: LBracket_distance_matrix.csv
  metric: euclidean

embeddings:
- name: tsne
  format: csv
  file: lbracket_tsne_layout.csv