name: Cantilever Beam

samples:
  count: 1000

parameters:
  format: csv
  file: CantileverBeam_design_parameters.csv

qois:
  format: csv
  file: CantileverBeam_QoIs.csv

thumbnails:
   format: png
   files: images/?.png
   padZeroes: false
   offset: 1

distances:
     format: csv
     file: CantileverBeam_distance_matrix.csv
     metric: euclidean

embeddings:
  - name: tsne
    format: csv
    file: CantileverBeam_tsne_layout.csv
