name: Rocket

samples:
  count: 1000

parameters:
  format: csv
  file: rocket_supershapes_design_parameters.csv

qois:
  format: csv
  file: rocket_supershapes_QoIs.csv

thumbnails:
  format: png
  files: images/?.png
  padZeroes: false
  offset: 1

distances:
  format: csv
  file: rocket_supershapes_distance_matrix.csv
  metric: euclidean

embeddings:
- name: tsne
  format: csv
  file: rocket_tsne_layout.csv

