name: Grain

samples:
  count: 400

qois:
  - name: Percent Fractured
    format: csv
    file: QOI_400.csv

thumbnails:
  format: png
  files: images/?.png
  padZeroes: false
  offset: 1

distances:
  format: csv
  file: NewdistanceMatrix.csv
  metric: euclidean

embeddings:
- name: tsne
  format: csv
  file: New_tsne_layout.csv

