name: Grain

samples:
  count: 400

qois:
  - name: Percent Fractured
    format: csv
    file: QOI_400.csv

thumbnails:
  format: png
  files: images/?.png
  padZeroes: false
  offset: 1

distances:
  format: csv
  file: distanceMatrix_400.csv
  metric: euclidean

embeddings:
- name: tsne
  format: csv
  file: tsne_layout_400.csv

